name: cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Heroku
        uses: actions/checkout@v2
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: "campusmaps"
            heroku_email: "me@chrisc.dev"